### ISSUE TITLE
Duplicate CSS classes: gap-m, gap-col-m, gap-y-m

### ISSUE THREAD

**Issue by web-padawan** [anezthes/lumo-css-framework#1]
Originally reported by a user in Discord. The following classes are duplicates:

https://github.com/anezthes/lumo-css-framework/blob/943d9986e0e6f83c59232516fbe101c6604f2d7e/classes.css#L353-L358

https://github.com/anezthes/lumo-css-framework/blob/943d9986e0e6f83c59232516fbe101c6604f2d7e/classes.css#L370-L375

https://github.com/anezthes/lumo-css-framework/blob/943d9986e0e6f83c59232516fbe101c6604f2d7e/classes.css#L387-L392

**Comment by anezthes** [comment]
Fixed in https://github.com/anezthes/lumo-css-framework/commit/417c9ed70a91f5da56d311e3099ec3c363ebb0c8.
